### ISSUE TITLE
Test environment  

### ISSUE THREAD

**Issue by artrayme** [Inejka/crawlviewer#1]
Hi!
Please, fix the test environment for test_app.py. Your warning is a piece of ...
![image](https://github.com/Inejka/crawlviewer/assets/78550819/4218c0ef-85c9-49fa-9954-5fb64c85cd1e)

I've just erased all data from disk C. My windows system is totally crushed. So, I have to use Arch Linux because of your bad test environment (and BTW I use Arch).

**Comment by Inejka** [comment]
fixed with 2f9388b

**Comment by artrayme** [comment]
Thank you a lot! 
But anyway, I still use Arch Linux
